In [1]:
import numpy as np

In [2]:
#Vstack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [5]:
#hstack
import numpy as geek
  
rr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print (rr1) 
  
rr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print (rr2) 
  
# Stacking the two arrays horizontally
out_arr = geek.hstack((rr1,rr2))
print ("Output stacked array :\n ", out_arr)

[[ 1  2  3]
 [-1 -2 -3]]
[[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [9]:
np.tile(np.arange(1,12).reshape(11,1),20)

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
         9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11

In [10]:
# Transpose
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
#flat
array = geek.arange(15).reshape(3, 5)
array
 
print(array.flat[0:15])        
 
print(type(array.flat))
 
for i in array.flat:
    print(i, end = ' ')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.flatiter'>
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [16]:
a = np.array([[1,2], [3,4]])
a.flatten()
a.flatten('F')


array([1, 3, 2, 4])

In [18]:
#broadcast
x = np.array([1, 2, 3])
np.broadcast_to(x, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [21]:
#numpy _squeeze
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [24]:
print(np.squeeze(x).shape)
print(np.squeeze(x))

(3,)
[0 1 2]


In [23]:
np.squeeze(x, axis=0).shape

(3, 1)

In [27]:
#concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b.T), axis=1))
print(np.concatenate((a, b), axis=None))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


In [29]:
#np.repeat
np.repeat(3,4)

array([3, 3, 3, 3])

In [31]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [32]:
np.repeat(x, 2)


array([[1, 2],
       [3, 4],
       [3, 4]])

In [33]:
np.repeat(x, 3, axis=1)


array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [34]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [35]:
# np.append()
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))


array([[0, 1, 2],
       [3, 0, 1]])

In [40]:
np.resize(a,(1,4))

array([[0, 1, 2, 3]])

In [41]:
np.resize(a,(2,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [43]:
x = np.arange(16.0).reshape(4, 4)
print(x)
print(np.hsplit(x, 2))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [44]:
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [45]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [46]:
np.hsplit(x, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]),
 array([[[2., 3.]],
 
        [[6., 7.]]])]

In [47]:
#dsplit
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [48]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [49]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]),
 array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]),
 array([], shape=(2, 2, 0), dtype=float64)]

In [50]:
#swap axes
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [51]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [52]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])