In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)
print(z)

[5, 7, 9, 11]


In [2]:
import numpy as np
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [3]:
def myadd(x, y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [4]:
print(type(np.add))

<class 'numpy.ufunc'>


In [5]:
print(type(np.concatenate))

<class 'function'>


In [6]:
if type(np.add) == np.ufunc:
    print('add is ufunc')
else:
    print('add is not ufunc')

add is ufunc


In [7]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [8]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)
print(newarr)

[-10  -1   8  17  26  35]


In [9]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
print(newarr)

[ 200  420  660  920 1200 1500]


In [10]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [11]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to 
the values in the second array, 
and return the results in a new array.

In [12]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [13]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [14]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [15]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


In [16]:
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [17]:
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [18]:
arr = np.around(3.1666, 2)
print(arr)

3.17


In [19]:
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [20]:
# The ceil() function rounds off decimal to nearest upper integer.
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


In [21]:
# Use the log2() function to perform log at the base 2
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [22]:
# Use the log10() function to perform log at the base 10.
arr = np.arange(1, 10)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [23]:
# Use the log() function to perform log at the base e.
arr = np.arange(1, 10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [24]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

1.7005483074552052


In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])

print(newarr)

12


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=0)

print(newarr)

[2 4 6]


In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [29]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


In [30]:
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)

print(x)

24


In [31]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])

print(x)

40320


In [32]:
# If you specify axis=1, NumPy will return the product of each array.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [33]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=0)

print(newarr)

[ 5 12 21 32]


In [34]:
arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [35]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


We can perform this operation repeatedly by giving parameter n.
E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, 
we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

In [36]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=1)

print(newarr)

[  5  10 -20]


In [37]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


In [38]:
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

12


In [39]:
# To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)

print(x)

18


In [40]:
arr = np.arange(1, 11)
x = np.lcm.reduce(arr)

print(x)

2520


In [41]:
# Finding GCD (Greatest Common Denominator)
# The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of 
# the numbers.

num1 = 6
num2 = 9
x = np.gcd(num1, num2)

print(x)

3


In [42]:
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)

print(x)

4


In [43]:
x = np.sin(np.pi/2)
print(x)

1.0


In [44]:
arr = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
x= np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [45]:
arr = np.deg2rad(arr)
x= np.deg2rad(arr)
print(x)

[0.00047849 0.00031899 0.00023925 0.0001914 ]


In [46]:
arr = np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
x=np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [47]:
x = np.arcsin(1.0)
x

1.5707963267948966

In [48]:
arr = np.array([1,-1,0.1])
x = np.arcsin(arr)
x

array([ 1.57079633, -1.57079633,  0.10016742])

In [49]:
base = 3
perp = 4
x=np.hypot(base,perp)
x

5.0

In [50]:
x = np.sinh(np.pi/2)
x

2.3012989023072947

In [51]:
arr = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
x= np.cosh(arr)
x

array([2.50917848, 1.60028686, 1.32460909, 1.20397209])

In [52]:
x = np.arcsinh(1.0)
x

0.881373587019543

In [53]:
arr = np.array([0.1,0.2,0.5])
x = np.arctanh(arr)
print(x)

[0.10033535 0.20273255 0.54930614]


In [54]:
arr = np.array([1,1,1,2,3,3,5,5,6,7])
x = np.unique(arr)
x

array([1, 2, 3, 5, 6, 7])

In [55]:
# Find unique vaalues of the two arrays
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

newrr = np.union1d(arr1,arr2)
print(newarr)

[  5 -30]


In [56]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

newrr1= np.intersect1d(arr1,arr2,assume_unique=True)
print(newrr1)

[3 4]


In [57]:
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])

newrr2 = np.setdiff1d(arr1,arr2,assume_unique=True)
print(newrr2)

[1 2]


In [58]:
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])

newrr3 = np.setxor1d(arr1,arr2,assume_unique=True)
print(newrr3)

[1 2 5 6]
